pluginGroup=com.onlinealarmkur.idea
pluginVersion=1.0.0
pluginRepositoryUrl=https://github.com/onlinealarmkur/jetbrains-alarm-timer
kotlin.stdlib.default.dependency=false
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
platformVersion=2025.2.6.2
jdkVersion=25
